name: dentalrecognitionproject
description: Dental Recoginition

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.1.0
  image_picker: ^1.0.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0
  get: ^4.6.5
  

  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/flags/
